### ISSUE TITLE
xarray 0.19.0 does not import on python3.6 -- SyntaxError: future feature annotations is not defined

### ISSUE THREAD

**Issue by akrherz** [conda-forge/xarray-feedstock#65]
Issue: Can't import xarray 0.19.0 on python 3.6

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /opt/miniconda3/envs/py36dev:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
ca-certificates           2021.5.30            ha878542_0    conda-forge
certifi                   2021.5.30        py36h5fab9bb_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_1    conda-forge
libblas                   3.9.0                9_openblas    conda-forge
libcblas                  3.9.0                9_openblas    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 11.1.0               hc902ee8_2    conda-forge
libgfortran-ng            11.1.0               h69a702a_0    conda-forge
libgfortran5              11.1.0               h6c583b3_0    conda-forge
libgomp                   11.1.0               hc902ee8_2    conda-forge
liblapack                 3.9.0                9_openblas    conda-forge
libopenblas               0.3.15          pthreads_h8fe5266_1    conda-forge
libstdcxx-ng              11.1.0               h56837e0_2    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
numpy                     1.19.5           py36hfc0c790_2    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
pandas                    1.1.5            py36h284efc9_0    conda-forge
pip                       21.2.1             pyhd8ed1ab_0    conda-forge
python                    3.6.13          hffdb5ce_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.6                     2_cp36m    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
setuptools                49.6.0           py36h5fab9bb_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.36.0               h9cd32fc_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xarray                    0.19.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : py36dev
    active env location : /opt/miniconda3/envs/py36dev
            shell level : 2
       user config file : /home/akrherz/.condarc
 populated config files : /home/akrherz/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.8.10.final.0
       virtual packages : __linux=4.18.0=0
                          __glibc=2.28=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/miniconda3  (writable)
      conda av data dir : /opt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/miniconda3/pkgs
                          /home/akrherz/.conda/pkgs
       envs directories : /opt/miniconda3/envs
                          /home/akrherz/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.8.10 Linux/4.18.0-305.10.2.el8_4.x86_64 rhel/8.4 glibc/2.28
                UID:GID : 43306:101
             netrc file : /home/akrherz/.netrc
           offline mode : False
```
</details>

```
$ conda create -n py36dev python=3.6 xarray
$ conda activate py36dev
$ python
>>> import xarray
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/py36dev/lib/python3.6/site-packages/xarray/__init__.py", line 3, in <module>
    from . import testing, tutorial, ufuncs
  File "/opt/miniconda3/envs/py36dev/lib/python3.6/site-packages/xarray/testing.py", line 9, in <module>
    from xarray.core.dataarray import DataArray
  File "/opt/miniconda3/envs/py36dev/lib/python3.6/site-packages/xarray/core/dataarray.py", line 24, in <module>
    from . import (
  File "/opt/miniconda3/envs/py36dev/lib/python3.6/site-packages/xarray/core/computation.py", line 4
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

**Comment by akrherz** [comment]
Appears to me that current xarray [requires python>=3.7](https://github.com/pydata/xarray/blob/stable/setup.cfg#L77)

**Comment by ReimarBauer** [comment]
Got on this over metpy. 
metpy.units has a dependency to xarray.

**Comment by dopplershift** [comment]
@ReimarBauer The metadata for xarray 0.19.0 build 0 has been patched so it's no longer capable to install xarray 0.19 from conda-forge in a Python 3.6 environment.
